# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import base.fields
import util.fields
import util.mixins
from django.conf import settings
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0002_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_accessaccount_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_accessaccount_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_accessaccount_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
            ],
            options={
                'verbose_name': 'access account',
                'verbose_name_plural': 'access accounts',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_accessrole_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_accessrole_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('groups', models.ManyToManyField(verbose_name='groups', to='auth.Group', help_text='List of groups used by the role')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_accessrole_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
            ],
            options={
                'verbose_name': 'access role',
                'verbose_name_plural': 'access roles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('default', models.BooleanField(default=False, verbose_name='default', help_text='Is this menu item is always displayed ?')),
                ('path', models.CharField(help_text='Menu item link', verbose_name='path', max_length=127)),
                ('icon', models.CharField(help_text='Icon (font-awesome)', verbose_name='icon', max_length=31)),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('application', models.BooleanField(default=True, verbose_name='Is this module a main application ?', help_text='Is this module an application ?')),
                ('monthly_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price', help_text='Module price')),
                ('yearly_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='price', help_text='Module price')),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_module_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_module_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('dependencies', models.ManyToManyField(related_name='dependencies_rel_set', verbose_name='Dependencies', to='saas.Module', help_text='List of modules required to make this one work')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_module_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
                ('status', util.fields.StatusField(to='util.Status', related_name='status_saas_module_set', verbose_name='status')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('message', models.TextField(verbose_name='message', help_text='Message')),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_notification_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_notification_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_notification_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
                ('status', util.fields.StatusField(to='util.Status', related_name='status_saas_notification_set', verbose_name='status')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('avatar_height', models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='avatar height', editable=False)),
                ('avatar_width', models.PositiveSmallIntegerField(null=True, blank=True, verbose_name='avatar width', editable=False)),
                ('avatar', models.ImageField(null=True, upload_to=util.mixins.AvatarMixin.compute_upload_path, blank=True, max_length=64, width_field='avatar_width', height_field='avatar_height', verbose_name='avatar', help_text='Avatar')),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_profile_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_profile_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_profile_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
                ('locale', models.ForeignKey(to='util.Locale', help_text='Locale', related_name='saas_profile_set', verbose_name='locale')),
                ('notifications', models.ManyToManyField(blank=True, verbose_name='notifications', to='saas.Notification', help_text='Notifications')),
                ('timezone', models.ForeignKey(to='util.TimeZone', help_text='Timezone', related_name='saas_profile_set', verbose_name='timezone')),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL, help_text='User linked to this profile', related_name='profile', verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('referrer', models.EmailField(blank=True, help_text='Email of the person who recommended this site', verbose_name='referrer', max_length=75)),
                ('company_name', models.CharField(blank=True, help_text='Company name if the subscription is on behalf a company', verbose_name='company name', max_length=127)),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_subscriptioncategory_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_subscriptioncategory_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_subscriptioncategory_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
                ('status', util.fields.StatusField(to='util.Status', related_name='status_saas_subscriptioncategory_set', verbose_name='status')),
            ],
            options={
                'verbose_name': 'subscription category',
                'verbose_name_plural': 'subscription categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('page_title', models.CharField(help_text='Title of the page', verbose_name='page title', max_length=127)),
                ('page_description', models.CharField(help_text='Description of the page (250 characters max, 200 ideally)', verbose_name='page description', max_length=250)),
            ],
            options={
                'verbose_name': 'view',
                'verbose_name_plural': 'views',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ViewContext',
            fields=[
                ('id', models.AutoField(serialize=False, auto_created=True, primary_key=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now, auto_now_add=True, verbose_name='created on', help_text='Date of creation')),
                ('last_modified_on', models.DateTimeField(auto_now=True, default=django.utils.timezone.now, verbose_name='last modified on', help_text='Date of last modification')),
                ('deleted_on', models.DateTimeField(null=True, blank=True, verbose_name='deleted on', editable=False, help_text='Date of deletion')),
                ('active', models.BooleanField(default=True, verbose_name='active', editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', verbose_name='label', max_length=32)),
                ('name', models.CharField(unique=True, help_text='Unique name, used in imports/exports features', verbose_name='name', editable=False, max_length=255)),
                ('created_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_viewcontext_set', verbose_name='created by', editable=False, help_text='The user who created this data')),
                ('deleted_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_viewcontext_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data')),
                ('last_modified_by', base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_viewcontext_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data')),
            ],
            options={
                'verbose_name': 'view context',
                'verbose_name_plural': 'view contexts',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='view',
            name='context',
            field=models.ForeignKey(to='saas.ViewContext', help_text='Context of the menu Item', related_name='view_set', verbose_name='context'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='created_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_view_set', verbose_name='created by', editable=False, help_text='The user who created this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='deleted_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_view_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='last_modified_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_view_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='module',
            field=models.ForeignKey(to='saas.Module', help_text='Module of the view', related_name='view_set', verbose_name='module'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='page_keywords',
            field=models.ManyToManyField(blank=True, related_name='view_set', verbose_name='page keywords', to='util.Keyword', help_text='List of keywords used by the page'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='resources_config',
            field=models.ForeignKey(blank=True, to='util.HttpResourcesConfig', help_text='List of resources used by this view (CSS, JS, Meta, ...)', related_name='view_set', verbose_name='HTTP resources configuration'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(to='saas.SubscriptionCategory', help_text='Subscription category', related_name='saas_subscription_set', verbose_name='category'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_subscription_set', verbose_name='created by', editable=False, help_text='The user who created this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_subscription_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_modified_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_subscription_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='modules',
            field=models.ManyToManyField(related_name='saas_subscription_set', verbose_name='modules', to='saas.Module', help_text='List of module installed on the subscription'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, help_text='Subscription owner', related_name='saas_subscription_set', verbose_name='owner'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=util.fields.StatusField(to='util.Status', related_name='status_saas_subscription_set', verbose_name='status'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='context',
            field=models.ForeignKey(to='saas.ViewContext', help_text='Context of the menu Item', related_name='menu_item_set', verbose_name='context'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='created_saas_menuitem_set', verbose_name='created by', editable=False, help_text='The user who created this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='deleted_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='deleted_saas_menuitem_set', verbose_name='deleted by', editable=False, help_text='The user who deleted this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_modified_by',
            field=base.fields.UserField(null=True, to=settings.AUTH_USER_MODEL, related_name='last_modified_saas_menuitem_set', verbose_name='last modified by', editable=False, help_text='The user who last modified this data'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(null=True, blank=True, to='saas.MenuItem', related_name='directory_set', verbose_name='parent', help_text='Parent directory'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='views',
            field=models.ManyToManyField(blank=True, related_name='menu_item_set', verbose_name='views', to='saas.View', help_text='Views related to this menu item'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessrole',
            name='module',
            field=models.ForeignKey(to='saas.Module', help_text='Module creating the role', related_name='saas_access_role_set', verbose_name='module'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='role',
            field=models.ForeignKey(to='saas.AccessRole', help_text='Role linked to this account', related_name='saas_access_account_set', verbose_name='role'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='status',
            field=util.fields.StatusField(to='util.Status', related_name='status_saas_accessaccount_set', verbose_name='status'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='subscription',
            field=models.ForeignKey(to='saas.Subscription', help_text='Role linked to this account', related_name='saas_access_account_set', verbose_name='subscription'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, help_text='user who owns this account', related_name='saas_access_account_set', verbose_name='user'),
            preserve_default=True,
        ),
    ]
