# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone
import base.fields
from django.conf import settings
import util.fields
import util.mixins


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0001_initial'),
        ('util', '0002_imports'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_accessaccount_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_accessaccount_set', help_text='The user who deleted this data', editable=False)),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_accessaccount_set', help_text='The user who last modified this data', editable=False)),
            ],
            options={
                'verbose_name': 'access account',
                'verbose_name_plural': 'access accounts',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_accessrole_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_accessrole_set', help_text='The user who deleted this data', editable=False)),
                ('groups', models.ManyToManyField(verbose_name='groups', to='auth.Group', help_text='List of groups used by the role')),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_accessrole_set', help_text='The user who last modified this data', editable=False)),
            ],
            options={
                'verbose_name': 'access role',
                'verbose_name_plural': 'access roles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('default', models.BooleanField(verbose_name='default', default=False, help_text='Is this menu item is always displayed ?')),
                ('path', models.CharField(verbose_name='path', max_length=127, help_text='Menu item link')),
                ('icon', models.CharField(verbose_name='icon', max_length=31, help_text='Icon (font-awesome)')),
            ],
            options={
                'verbose_name': 'menu item',
                'verbose_name_plural': 'menu items',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('application', models.BooleanField(verbose_name='Is this module a main application ?', default=True, help_text='Is this module an application ?')),
                ('monthly_price', models.DecimalField(verbose_name='price', max_digits=5, decimal_places=2, help_text='Module price')),
                ('yearly_price', models.DecimalField(verbose_name='price', max_digits=5, decimal_places=2, help_text='Module price')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_module_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_module_set', help_text='The user who deleted this data', editable=False)),
                ('dependencies', models.ManyToManyField(verbose_name='Dependencies', to='saas.Module', related_name='dependencies_rel_set', help_text='List of modules required to make this one work')),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_module_set', help_text='The user who last modified this data', editable=False)),
                ('status', util.fields.StatusField(to='util.Status', verbose_name='status', related_name='status_saas_module_set')),
            ],
            options={
                'verbose_name': 'module',
                'verbose_name_plural': 'modules',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('message', models.TextField(verbose_name='message', help_text='Message')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_notification_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_notification_set', help_text='The user who deleted this data', editable=False)),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_notification_set', help_text='The user who last modified this data', editable=False)),
                ('status', util.fields.StatusField(to='util.Status', verbose_name='status', related_name='status_saas_notification_set')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('avatar_height', models.PositiveSmallIntegerField(blank=True, verbose_name='avatar height', null=True, editable=False)),
                ('avatar_width', models.PositiveSmallIntegerField(blank=True, verbose_name='avatar width', null=True, editable=False)),
                ('avatar', models.ImageField(verbose_name='avatar', max_length=64, width_field='avatar_width', null=True, blank=True, help_text='Avatar', upload_to=util.mixins.AvatarMixin.compute_upload_path, height_field='avatar_height')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_profile_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_profile_set', help_text='The user who deleted this data', editable=False)),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_profile_set', help_text='The user who last modified this data', editable=False)),
                ('locale', models.ForeignKey(to='util.Locale', help_text='Locale', verbose_name='locale', related_name='saas_profile_set')),
                ('notifications', models.ManyToManyField(blank=True, verbose_name='notifications', to='saas.Notification', help_text='Notifications')),
                ('timezone', models.ForeignKey(to='util.TimeZone', help_text='Timezone', verbose_name='timezone', related_name='saas_profile_set')),
                ('user', models.OneToOneField(to=settings.AUTH_USER_MODEL, help_text='User linked to this profile', verbose_name='user', related_name='profile')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('referrer', models.EmailField(blank=True, verbose_name='referrer', max_length=75, help_text='Email of the person who recommended this site')),
                ('company_name', models.CharField(blank=True, verbose_name='company name', max_length=127, help_text='Company name if the subscription is on behalf a company')),
            ],
            options={
                'verbose_name': 'subscription',
                'verbose_name_plural': 'subscriptions',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_subscriptioncategory_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_subscriptioncategory_set', help_text='The user who deleted this data', editable=False)),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_subscriptioncategory_set', help_text='The user who last modified this data', editable=False)),
                ('status', util.fields.StatusField(to='util.Status', verbose_name='status', related_name='status_saas_subscriptioncategory_set')),
            ],
            options={
                'verbose_name': 'subscription category',
                'verbose_name_plural': 'subscription categories',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('page_title', models.CharField(verbose_name='page title', max_length=127, help_text='Title of the page')),
                ('page_description', models.CharField(verbose_name='page description', max_length=250, help_text='Description of the page (250 characters max, 200 ideally)')),
            ],
            options={
                'verbose_name': 'view',
                'verbose_name_plural': 'views',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ViewContext',
            fields=[
                ('id', models.AutoField(verbose_name='ID', primary_key=True, serialize=False, auto_created=True)),
                ('created_on', models.DateTimeField(verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now, auto_now_add=True)),
                ('last_modified_on', models.DateTimeField(verbose_name='last modified on', auto_now=True, help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(blank=True, verbose_name='deleted on', editable=False, null=True, help_text='Date of deletion')),
                ('active', models.BooleanField(verbose_name='active', default=True, editable=False, help_text='Is the data usable ?')),
                ('label', models.CharField(verbose_name='label', max_length=32, help_text='The way the data will be see from foreign objects')),
                ('name', models.CharField(verbose_name='name', max_length=255, editable=False, unique=True, help_text='Unique name, used in imports/exports features')),
                ('created_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_viewcontext_set', help_text='The user who created this data', editable=False)),
                ('deleted_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_viewcontext_set', help_text='The user who deleted this data', editable=False)),
                ('last_modified_by', base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_viewcontext_set', help_text='The user who last modified this data', editable=False)),
            ],
            options={
                'verbose_name': 'view context',
                'verbose_name_plural': 'view contexts',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='view',
            name='context',
            field=models.ForeignKey(to='saas.ViewContext', help_text='Context of the menu Item', verbose_name='context', related_name='view_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='created_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_view_set', help_text='The user who created this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='deleted_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_view_set', help_text='The user who deleted this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='last_modified_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_view_set', help_text='The user who last modified this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='module',
            field=models.ForeignKey(to='saas.Module', help_text='Module of the view', verbose_name='module', related_name='view_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='page_keywords',
            field=models.ManyToManyField(blank=True, verbose_name='page keywords', related_name='view_set', to='util.Keyword', help_text='List of keywords used by the page'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='resources_config',
            field=models.ForeignKey(verbose_name='HTTP resources configuration', help_text='List of resources used by this view (CSS, JS, Meta, ...)', blank=True, related_name='view_set', to='util.HttpResourcesConfig'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(to='saas.SubscriptionCategory', help_text='Subscription category', verbose_name='category', related_name='saas_subscription_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_subscription_set', help_text='The user who created this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_subscription_set', help_text='The user who deleted this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_modified_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_subscription_set', help_text='The user who last modified this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='modules',
            field=models.ManyToManyField(verbose_name='modules', to='saas.Module', help_text='List of module installed on the subscription'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, help_text='Subscription owner', verbose_name='owner', related_name='saas_subscription_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=util.fields.StatusField(to='util.Status', verbose_name='status', related_name='status_saas_subscription_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='context',
            field=models.ForeignKey(to='saas.ViewContext', help_text='Context of the menu Item', verbose_name='context', related_name='menu_item_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='created by', related_name='created_saas_menuitem_set', help_text='The user who created this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='deleted_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='deleted by', related_name='deleted_saas_menuitem_set', help_text='The user who deleted this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_modified_by',
            field=base.fields.UserField(to=settings.AUTH_USER_MODEL, null=True, verbose_name='last modified by', related_name='last_modified_saas_menuitem_set', help_text='The user who last modified this data', editable=False),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(verbose_name='parent', null=True, blank=True, related_name='directory_set', help_text='Parent directory', to='saas.MenuItem'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='views',
            field=models.ManyToManyField(blank=True, verbose_name='views', related_name='menu_item_set', to='saas.View', help_text='Views related to this menu item'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='role',
            field=models.ForeignKey(to='saas.AccessRole', help_text='Role linked to this account', verbose_name='role', related_name='saas_access_account_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='status',
            field=util.fields.StatusField(to='util.Status', verbose_name='status', related_name='status_saas_accessaccount_set'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='subscription',
            field=models.ForeignKey(to='saas.Subscription', help_text='Role linked to this account', verbose_name='subscription'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='user',
            field=models.ForeignKey(to=settings.AUTH_USER_MODEL, help_text='user who owns this account', verbose_name='user', related_name='saas_access_account_set'),
            preserve_default=True,
        ),
    ]
