# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import base.fields
import django.utils.timezone
import util.mixins
from django.conf import settings
import util.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('util', '0002_imports'),
        ('auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessAccount',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('created_by', base.fields.UserField(related_name='created_saas_accessaccount_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_accessaccount_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_accessaccount_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'access accounts',
                'verbose_name': 'access account',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AccessRole',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('created_by', base.fields.UserField(related_name='created_saas_accessrole_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_accessrole_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('groups', models.ManyToManyField(help_text='List of groups used by the role', to='auth.Group', verbose_name='groups')),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_accessrole_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'access roles',
                'verbose_name': 'access role',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('default', models.BooleanField(help_text='Is this menu item is always displayed ?', verbose_name='default', default=False)),
                ('icon', models.CharField(help_text='Icon (font-awesome)', max_length=31, verbose_name='icon')),
            ],
            options={
                'verbose_name_plural': 'menu items',
                'verbose_name': 'menu item',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('application', models.BooleanField(help_text='Is this module an application ?', verbose_name='Is this module a main application ?', default=True)),
                ('monthly_price', models.DecimalField(help_text='Module price', max_digits=5, decimal_places=2, verbose_name='price')),
                ('yearly_price', models.DecimalField(help_text='Module price', max_digits=5, decimal_places=2, verbose_name='price')),
                ('created_by', base.fields.UserField(related_name='created_saas_module_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_module_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('dependencies', models.ManyToManyField(help_text='List of modules required to make this one work', related_name='dependencies_rel_set', to='saas.Module', verbose_name='Dependencies')),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_module_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('status', util.fields.StatusField(related_name='status_saas_module_set', verbose_name='status', to='util.Status')),
            ],
            options={
                'verbose_name_plural': 'modules',
                'verbose_name': 'module',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('message', models.TextField(help_text='Message', verbose_name='message')),
                ('created_by', base.fields.UserField(related_name='created_saas_notification_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_notification_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_notification_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('status', util.fields.StatusField(related_name='status_saas_notification_set', verbose_name='status', to='util.Status')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('avatar_height', models.PositiveSmallIntegerField(editable=False, null=True, blank=True, verbose_name='avatar height')),
                ('avatar_width', models.PositiveSmallIntegerField(editable=False, null=True, blank=True, verbose_name='avatar width')),
                ('avatar', models.ImageField(null=True, upload_to=util.mixins.AvatarMixin.compute_upload_path, verbose_name='avatar', help_text='Avatar', height_field='avatar_height', width_field='avatar_width', blank=True, max_length=64)),
                ('created_by', base.fields.UserField(related_name='created_saas_profile_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_profile_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_profile_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('locale', models.ForeignKey(related_name='saas_profile_set', verbose_name='locale', help_text='Locale', to='util.Locale')),
                ('notifications', models.ManyToManyField(help_text='Notifications', blank=True, to='saas.Notification', verbose_name='notifications')),
                ('timezone', models.ForeignKey(related_name='saas_profile_set', verbose_name='timezone', help_text='Timezone', to='util.TimeZone')),
                ('user', models.OneToOneField(related_name='profile', verbose_name='user', help_text='User linked to this profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'profiles',
                'verbose_name': 'profile',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('referrer', models.EmailField(help_text='Email of the person who recommended this site', max_length=75, blank=True, verbose_name='referrer')),
                ('company_name', models.CharField(help_text='Company name if the subscription is on behalf a company', max_length=127, blank=True, verbose_name='company name')),
            ],
            options={
                'verbose_name_plural': 'subscriptions',
                'verbose_name': 'subscription',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='SubscriptionCategory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('created_by', base.fields.UserField(related_name='created_saas_subscriptioncategory_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_subscriptioncategory_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_subscriptioncategory_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('status', util.fields.StatusField(related_name='status_saas_subscriptioncategory_set', verbose_name='status', to='util.Status')),
            ],
            options={
                'verbose_name_plural': 'subscription categories',
                'verbose_name': 'subscription category',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('page_title', models.CharField(help_text='Title of the page', max_length=127, verbose_name='page title')),
                ('page_description', models.CharField(help_text='Description of the page (250 characters max, 200 ideally)', max_length=250, verbose_name='page description')),
            ],
            options={
                'verbose_name_plural': 'views',
                'verbose_name': 'view',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='ViewContext',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, auto_created=True, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, verbose_name='created on', help_text='Date of creation', default=django.utils.timezone.now)),
                ('last_modified_on', models.DateTimeField(auto_now=True, verbose_name='last modified on', help_text='Date of last modification', default=django.utils.timezone.now)),
                ('deleted_on', models.DateTimeField(help_text='Date of deletion', editable=False, null=True, blank=True, verbose_name='deleted on')),
                ('active', models.BooleanField(help_text='Is the data usable ?', editable=False, verbose_name='active', default=True)),
                ('label', models.CharField(help_text='The way the data will be see from foreign objects', max_length=32, verbose_name='label')),
                ('name', models.CharField(help_text='Unique name, used in imports/exports features', editable=False, max_length=255, unique=True, verbose_name='name')),
                ('created_by', base.fields.UserField(related_name='created_saas_viewcontext_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('deleted_by', base.fields.UserField(related_name='deleted_saas_viewcontext_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL)),
                ('last_modified_by', base.fields.UserField(related_name='last_modified_saas_viewcontext_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'view contexts',
                'verbose_name': 'view context',
            },
            bases=(models.Model,),
        ),
        migrations.AddField(
            model_name='view',
            name='context',
            field=models.ForeignKey(related_name='view_set', verbose_name='context', help_text='Context of the menu Item', to='saas.ViewContext'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='created_by',
            field=base.fields.UserField(related_name='created_saas_view_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='deleted_by',
            field=base.fields.UserField(related_name='deleted_saas_view_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='last_modified_by',
            field=base.fields.UserField(related_name='last_modified_saas_view_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='module',
            field=models.ForeignKey(related_name='view_set', verbose_name='module', help_text='Module of the view', to='saas.Module'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='page_keywords',
            field=models.ManyToManyField(help_text='List of keywords used by the page', related_name='view_set', blank=True, to='util.Keyword', verbose_name='page keywords'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='view',
            name='resources_config',
            field=models.ForeignKey(related_name='view_set', verbose_name='HTTP resources configuration', help_text='List of resources used by this view (CSS, JS, Meta, ...)', blank=True, to='util.HttpResourcesConfig'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='category',
            field=models.ForeignKey(related_name='saas_subscription_set', verbose_name='category', help_text='Subscription category', to='saas.SubscriptionCategory'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='created_by',
            field=base.fields.UserField(related_name='created_saas_subscription_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='deleted_by',
            field=base.fields.UserField(related_name='deleted_saas_subscription_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_modified_by',
            field=base.fields.UserField(related_name='last_modified_saas_subscription_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='modules',
            field=models.ManyToManyField(help_text='List of module installed on the subscription', related_name='saas_subscription_set', to='saas.Module', verbose_name='modules'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='owner',
            field=models.ForeignKey(related_name='saas_subscription_set', verbose_name='owner', help_text='Subscription owner', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='subscription',
            name='status',
            field=util.fields.StatusField(related_name='status_saas_subscription_set', verbose_name='status', to='util.Status'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='context',
            field=models.ForeignKey(related_name='menu_item_set', verbose_name='context', help_text='Context of the menu Item', to='saas.ViewContext'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='created_by',
            field=base.fields.UserField(related_name='created_saas_menuitem_set', null=True, verbose_name='created by', help_text='The user who created this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='deleted_by',
            field=base.fields.UserField(related_name='deleted_saas_menuitem_set', null=True, verbose_name='deleted by', help_text='The user who deleted this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='last_modified_by',
            field=base.fields.UserField(related_name='last_modified_saas_menuitem_set', null=True, verbose_name='last modified by', help_text='The user who last modified this data', editable=False, to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(related_name='directory_set', null=True, verbose_name='parent', help_text='Parent directory', blank=True, to='saas.MenuItem'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='menuitem',
            name='view',
            field=models.ForeignKey(related_name='menu_items_set', verbose_name='views', help_text='View pointed by this menu item', blank=True, null=True, to='saas.View'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessrole',
            name='module',
            field=models.ForeignKey(related_name='saas_access_role_set', verbose_name='module', help_text='Module creating the role', to='saas.Module'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='role',
            field=models.ForeignKey(related_name='saas_access_account_set', verbose_name='role', help_text='Role linked to this account', to='saas.AccessRole'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='status',
            field=util.fields.StatusField(related_name='status_saas_accessaccount_set', verbose_name='status', to='util.Status'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='subscription',
            field=models.ForeignKey(related_name='saas_access_account_set', verbose_name='subscription', help_text='Role linked to this account', to='saas.Subscription'),
            preserve_default=True,
        ),
        migrations.AddField(
            model_name='accessaccount',
            name='user',
            field=models.ForeignKey(related_name='saas_access_account_set', verbose_name='user', help_text='user who owns this account', to=settings.AUTH_USER_MODEL),
            preserve_default=True,
        ),
    ]
